#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
python -V
export PATH=${OPENSHIFT_DATA_DIR}/bin:$PATH
python -V
chmod a+x ${OPENSHIFT_REPO_DIR}/diy/runserver.py
nohup ${OPENSHIFT_REPO_DIR}/diy/runserver.py> ${OPENSHIFT_DIY_LOG_DIR}/app.log 2>&1 &